### ISSUE TITLE
Skip link has duplicated 'main-content' elements is printed on the page

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#100]
Referenced from https://www.drupal.org/project/civictheme/issues/3415763
---

We have 2 target links rendered. There should be only one

<img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZTR2OXg4YWZmbGt3YTVqYm1vbWQ2bWxjem9xN3Q4OWhkdzlqZ3V0YyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/9Jmb2idg10qJSygvTQ/giphy.gif"/>

```
<a id="main-content" tabindex="-1"></a>
      
  
  <main class="ct-layout ct-theme-light ct-vertical-spacing--top " role="main">
    <a id="main-content" tabindex="-1"></a>

              
    <div class="ct-layout__inner ">
```

**Comment by AlexSkrypnyk** [comment]
@jcloys 
Could you please advise on this.

There was an a11y issue raised q while ago that the target anchor should be *after* the banner.

But the banner may contain some interactive elements that are not navigation links (CTA's, cards etc).

Should we move the link *before* banner (top of the banner)? In this case the navigation will still remain *above* the anchor and will be skipped for keyboard navigation.

**Comment by jcloys** [comment]
It has to also do with the page structure. The main landmark occurs below the banner so it should remain there. If you move the main landmark up then the banner can be included.

**Comment by AlexSkrypnyk** [comment]
@jcloys 
We can move the main landmark to the top of the banner to include it. The question was if we should do it, as Banner may contain some additional text apart from the title.

In this case, the user will be navigating to items in the following order:
1. Breadcrumbs within banner (if enabled) - tabbing through each item
2. Section title within banner (if enabled)
3. Page title as `<h1>` within banner
4. Banner content (if enabled) - could be anything that is allowed to be added to the banner as content, including a list of cards, each of which may have own parts through which a user will have to tab through.
5. Page content outside of the banner.

Currently, it goes to item 5 straight away, but we can move the landmark to include all the items from points 1-4.

**Comment by jcloys** [comment]
In this case go with 2 if enabled, but straight to 3 if not.

**Comment by AlexSkrypnyk** [comment]
@joshua-salsadigital 
Could you please move the `<a id="main-content" tabindex="-1"></a>` into the banner just above the Section title: https://github.com/civictheme/uikit/blob/main/components/03-organisms/banner/banner.twig#L94
