### ISSUE TITLE
Update navigation card `min` and `max` width

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#148]
The Navigation card sizes were updated in Figma 1.8 to contain min and max widths based on the total width of the card.

We need to update the Navigation card accordingly.

<img width="381" alt="Cursor_and_CivicTheme__Design_System_v1_8_0__WIP_" src="https://github.com/civictheme/uikit/assets/378794/a833a666-4dd6-42f5-8f13-6a52b5c75898">

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- Navigation card image grows width upto 30% of the container.

<img width="1231" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/ed8ac731-65f0-499f-b380-807987305817">
