### ISSUE TITLE
Storybook story is broken for AlertAPI

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#152]
### Summary

Storybook story is broken for AlertAPI

### Steps to reproduce

Go to https://uikit.civictheme.io/?path=/story/organisms-alert--alert-api

### Observed outcome

Observe that there are no alerts

### Expected outcome

Alerts should be shown

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- Alerts is shown as expected
<img width="1160" alt="Screenshot 2024-05-31 at 4 57 59 PM" src="https://github.com/civictheme/uikit/assets/51696317/c2efa7b0-6b82-4936-b620-a9100c40170d">
