### ISSUE TITLE
TOC is not rendered in Storybook

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#154]
### Summary

TOC is not rendered in Storybook

### Steps to reproduce

got to https://uikit.civictheme.io/?path=/story/molecules-table-of-contents--table-of-contents

### Observed outcome

only test data is rendered. TOC is not present on the page

### Expected outcome

TOC should be present on the page

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- TOC is present on the page
<img width="1199" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/01b18a3e-7a56-4e9e-8021-08b6a4625bba">
