### ISSUE TITLE
Banner background is not rendered in Storybook

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#155]
### Summary

Banner background is not rendered in Storybook

### Steps to reproduce

https://uikit.civictheme.io/?path=/story/organisms-banner--banner
Click on Background image

### Observed outcome

No background image is applied

### Expected outcome

Background image should be aplied

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- Background image is applied to Banner in Storybook for both light and dark themes.
<img width="1188" alt="Screenshot 2024-05-31 at 3 18 30 PM" src="https://github.com/civictheme/uikit/assets/51696317/3e762df0-3864-420f-9800-c13af57ddcbc">

**Comment by AlexSkrypnyk** [comment]
Fixed breadcrumbs
<img width="525" alt="Organisms___Banner_-_Banner_⋅_Storybook" src="https://github.com/civictheme/uikit/assets/378794/ed2e941a-2888-4125-88dd-23d58554b343">

**Comment by AlexSkrypnyk** [comment]
Also, added a capability to choose a theme for `Content` and `Content below`

<img width="630" alt="Organisms___Banner_-_Banner_⋅_Storybook" src="https://github.com/civictheme/uikit/assets/378794/4febe72a-d095-46e3-a959-6a6f6c84e76c">

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:

- Background image is applied to Banner in Storybook for both light and dark themes.
- Regression issue fixed : When 'breadcrumb' is checked
    1. Breadcrumb is rendering
    2. Props associated with breadcrumb is available under Breadcrumb tab
- Theme for `Content` and `Content below` is working fine
<img width="1220" alt="Screenshot 2024-06-03 at 12 26 24 PM" src="https://github.com/civictheme/uikit/assets/51696317/0247c801-8c8d-4a26-a003-2cda76579fbd">

<img width="1215" alt="Screenshot 2024-06-03 at 12 26 32 PM" src="https://github.com/civictheme/uikit/assets/51696317/321b9435-843a-4415-aa90-5510bbfdbe50">
