### ISSUE TITLE
Campaign text breaks out of the container in Storybook

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#156]
### Summary

Campaign text breaks out of the container in Storybook

### Steps to reproduce

https://uikit.civictheme.io/?path=/story/organisms-campaign--campaign

### Observed outcome

<img width="517" alt="Cursor_and_Organisms___Campaign_-_Campaign_⋅_Storybook" src="https://github.com/civictheme/uikit/assets/378794/8a4cdff2-a79e-474b-8f6d-0557a188a094">

### Expected outcome

-

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- Campaign text does not break out of the container.
- Works fine for different breakpoints.

https://github.com/civictheme/uikit/assets/51696317/8c82e174-17be-4799-9383-e4aadfd05a26
