### ISSUE TITLE
Social links icons missing on Footer page in Storybook

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#157]
### Summary

Social links icons missing on Footer page in Storybook

### Steps to reproduce

https://uikit.civictheme.io/?path=/story/organisms-footer--footer

### Observed outcome

<img width="519" alt="Organisms___Footer_-_Footer_⋅_Storybook" src="https://github.com/civictheme/uikit/assets/378794/01aa8960-84a1-4bfd-b048-51eedbc2c13c">

### Expected outcome

-

**Comment by AlexSkrypnyk** [comment]
Fixed in https://github.com/civictheme/uikit/pull/151

**Comment by AlexSkrypnyk** [comment]
@sonamchaturvedi28 
Please test https://6657ae480761dd55d9b9b0d2--civictheme-uikit.netlify.app/

**Comment by sonamchaturvedi28** [comment]
Test Env: Dev
Test Status: PASS
Test Result:
- Social links icons appear on Footer page in Storybook

<img width="1207" alt="Screenshot 2024-05-31 at 3 11 15 PM" src="https://github.com/civictheme/uikit/assets/51696317/314b3a1c-c312-4412-91a2-ce8b779b9cae">
