### ISSUE TITLE
"Image as Icon" is broken for Navigation card

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#169]
### Summary

In Storybook, "Image as Icon" is broken for Navigation card

### Steps to reproduce

-

### Observed outcome

<img width="550" alt="Molecules___Navigation_Card_-_Navigation_Card_⋅_Storybook" src="https://github.com/civictheme/uikit/assets/378794/fc6089f6-b242-4269-b505-b7412e5fe7cb">

### Expected outcome

Image should appear as icon

**Comment by AlexSkrypnyk** [comment]
The dimensions of the image are identical of an icon. This functionality was initially introduced to support non-SVG images on cards.

<img width="339" alt="Molecules___Navigation_Card_-_Navigation_Card_⋅_Storybook" src="https://github.com/civictheme/uikit/assets/378794/17cfe78c-3c70-4279-82d9-f5f0d129a59d">

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- "Image as Icon" appear as icon for Navigation card

<img width="1144" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/3836e4ae-a757-4251-aed1-ddc09731aed1">
