### ISSUE TITLE
Navigation card icon colour does not match the heading

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#172]
### Summary

As per design, Navigation card **icon colour should match the heading link colour** and it does not.

Also note that Navigation card story does not have an option to show title as a link, so it is not possible to see that the colour of the icon (once fixed) would be the colour of the link and **not the colour of the heading** (as per design).

<img width="366" alt="CivicTheme__Design_System_v1_8_0__WIP_" src="https://github.com/civictheme/uikit/assets/378794/0dde5431-1f75-4050-a5f6-8ac3afd9724f">

### Steps to reproduce

https://uikit.civictheme.io/?path=/story/molecules-navigation-card--navigation-card

### Observed outcome

<img width="278" alt="Molecules___Navigation_Card_-_Navigation_Card_⋅_Storybook" src="https://github.com/civictheme/uikit/assets/378794/a05f1873-d762-4ddc-8b50-cdb378d32f54">

### Expected outcome

<img width="277" alt="CivicTheme__Design_System_v1_8_0__WIP_" src="https://github.com/civictheme/uikit/assets/378794/76ed4012-55bf-4981-bc6e-bbcab7b99cf0">

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- Navigation card icon colour matches the heading link colour.

<img width="1087" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/6b0845eb-950c-4ad2-bd7a-c11e9e7d059b">
<img width="1152" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/b11c5e8c-47a0-4ba3-97c5-e21d26ff087b">
