### ISSUE TITLE
Form Element incorrectly generates the label display class

### ISSUE THREAD

**Issue by alan-cole** [civictheme/uikit#179]
### Summary

https://github.com/civictheme/uikit/blob/1409b2d2f1e46cbbdbcd4add17252abbd18cd072/components/02-molecules/form-element/form-element.twig#L25

On this line there's a single use of a `title_display` that is not mentioned elsewhere for form elements.

When rendering the output, `undefined` is returned as the classname it generates:

![Screenshot 2024-06-03 at 4 54 57 PM](https://github.com/civictheme/uikit/assets/12739575/6b3aa327-3901-428e-9161-edad2d1e27b7)

Given the rest of the line uses the prop `label_display`, I believe `title_display` is suppose to be `label_display`.

### Steps to reproduce

1. Go to https://uikit.civictheme.io/?path=/story/molecules-form-element--form-element
2. Observe the generated HTML for the default element:
```html
<div class="ct-form-element ct-theme-light ct-form-element--text  ct-form-element--label--undefined ct-form-element--label--after   ">
  <label class="ct-label ct-theme-light ct-label--regular ct-form-element__label" for="dolor">
    Label for input
  </label>
  <div class="ct-input ct-theme-light ct-input--default   ct-input--text ">
    <input type="text" value="Form element value" class="ct-textfield ct-input__element ct-theme-light   " placeholder="Form element placeholder">
  </div>
  <div class="ct-field-description ct-theme-light ct-form-element__description">
    Example input description
  </div>
</div>
```

### Observed outcome

It has `ct-form-element--label--undefined` as a class.

### Expected outcome

It should have `ct-form-element--label--before` as a class.

**Comment by AlexSkrypnyk** [comment]
@alan-cole 
Thank you for reporting this. We are currently working on the refactoring of the form components, so this issues will be tackled there.

**Comment by AlexSkrypnyk** [comment]
`Form element` is now `Field` and this functionality was removed.
https://github.com/civictheme/uikit/issues/58
