### ISSUE TITLE
Form Element label display "invisible" does not work

### ISSUE THREAD

**Issue by alan-cole** [civictheme/uikit#181]
### Summary

On this line https://github.com/civictheme/uikit/blob/main/components/02-molecules/form-element/form-element.twig#L38 there needs to be a space at the end of `ct-form-element__label` to prevent the `ct-visually-hidden` class being concatenated directly on the label class:

```html
<!-- ct-form-element__labelct-visually-hidden -->
<label class="ct-label ct-theme-light ct-label--regular ct-form-element__labelct-visually-hidden">
  Filter labels
</label>
````

### Steps to reproduce

1. Go to https://uikit.civictheme.io/?path=/story/molecules-form-element--form-element&knob-Label%20display_General=invisible

### Observed outcome

Label is not hidden

### Expected outcome

Label should be hidden.

**Comment by AlexSkrypnyk** [comment]
Thank you for reporting this. We are currently working on the refactoring of the form components, so this issues will be tackled there.

**Comment by fionamorrison23** [comment]
@AlexSkrypnyk noting there is no matching Jira issue for this one.

**Comment by AlexSkrypnyk** [comment]
`Form element` is now `Field` and this functionality was removed.
https://github.com/civictheme/uikit/issues/58
