### ISSUE TITLE
Update Single Filter to the 1.8 Designs.

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#184]
<img width="560" alt="Cursor_and_CivicTheme__Design_System_v1_8_0__WIP_" src="https://github.com/civictheme/uikit/assets/378794/c67d7a7b-8eff-4a2c-84d2-da36c33d4973">

## Solution diretion
- Update `Submit` button's icon placement.
- For `Reset` button, add prop to Twig: `reset_text: [string] Text on the reset button.` Only render this button if the `reset_text` value was provided.
- Implement JS make the buttons enabled/disabled when some/none of the filters are selected. Will need to use event listeners:
  1. Note that `Chip` already emits `ct.chip.dismiss` event for unchecking. This may need to be updated to include the checking as well as `ct.chip.select` event.
  2. The `Single filter` has a JS file as well - would need to subscribe to `ct.chip.dismiss` and `ct.chip.select` events to mark the Submit and Reset buttons as enabled/disabled.

**Comment by AlexSkrypnyk** [comment]
https://github.com/civictheme/uikit/assets/378794/1de18ef1-9212-43a3-bfa8-3a731c13f684

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: **Need Review**
Test Result:
- Single Filter is designed as expected - **PASS**.
- Submit and Reset buttons only renders when filter value is selected  - **PASS**.
- Submit and Reset buttons align as expected for different breakpoints with multiple filter options selected / unselected  - **PASS**.
- @AlexSkrypnyk All selected chip filters are not deselected when clicked on `Reset` button, is this expected? Will this be part of list component?  - **Need Review**

https://github.com/civictheme/uikit/assets/51696317/7ddf1cc8-6b6d-483d-b17e-d3dd0a5a33c6

**Comment by AlexSkrypnyk** [comment]
@sonamchaturvedi28 
Great pick up on those buttons. Thank you

Neither `Submit` nor `Reset` buttons will work in Storybook because there is no `<form>`element there. It should work correctly in Drupal.

Updated to the look of buttons on mobile
https://github.com/civictheme/uikit/pull/199
