### ISSUE TITLE
Add support for Left/Right rail to Layout

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#185]
<img width="700" alt="CivicTheme__Design_System_v1_8_0__WIP_" src="https://github.com/civictheme/uikit/assets/378794/256d5cfa-f483-4cc5-941b-8bcd09c93391">

<img width="172" alt="Cursor_and_CivicTheme__Design_System_v1_8_0__WIP_" src="https://github.com/civictheme/uikit/assets/378794/e473afb2-37b5-4654-b2c6-9183027fa590">

The layout should support a specific ordering of regions: the `content` region should always be the first in the markup for better SEO.

The mobile and desktop order of top and bottom rail regions may be different.

Solution direction
1. Replace `Sidebar` with 4 rail regions.
2. Use CSSGrid rules for the `Layout` component to set the order of the regions within mobile and desktop breakpoints.
3. Allow to set attributes on 4 new rail regions (in the same way as attributes were allowed to be passed as a `sidebar` prop).
4. Add backwards compatibility with `sidebar` within `Page` template.

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- `Sidebar` is replaced with 4 rail regions.
- `Attributes` are available on 4 new rail regions.
- Verified different permutation of enabled and disabled regions - when a rail region is disabled, the other region takes the full height. 
- Adding long content - blocks stay at the top.

<img width="1223" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/a02bbc65-44d2-4604-b56a-62c6a6545cde">

<img width="1428" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/036f29ad-65ec-415c-a37d-3fec86c7d85a">

<img width="1425" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/5537a030-d1ec-4dcd-87db-f56b4a7003b6">

<img width="1429" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/da36ca2d-1d68-45a8-9062-a34fe5855a22">
