### ISSUE TITLE
Side Navigation is missing left stripe.

### ISSUE THREAD

**Issue by alan-cole** [civictheme/uikit#201]
### Summary

The Side Navigation implementation does not look like the design:

Storybook:
https://uikit.civictheme.io/?path=/story/organisms-side-navigation--side-navigation

![Screenshot 2024-06-12 at 10 26 57 AM](https://github.com/civictheme/uikit/assets/12739575/a539674d-0915-4c16-86c4-21f57940f2c7)

Design:
https://www.figma.com/design/HJJPc5auJT2xbsbcjB5lZP/CivicTheme%3A-Design-System-v1.7.0?node-id=2976-42296&t=x9kmUhOgwBsRi5cb-0

![Screenshot 2024-06-12 at 10 26 48 AM](https://github.com/civictheme/uikit/assets/12739575/bd71c6c5-61d3-4fb5-b1a9-162da0bc79a5)

It seems to be missing a number of variables related to the stripe color (4px border on the left), e.g.

```scss
$ct-side-navigation-light-link-parent-stripe-color: ct-color-light('border-light');
$ct-side-navigation-light-link-parent-hover-stripe-color: ct-color-light('highlight');
$ct-side-navigation-light-link-child-stripe-color: ct-color-light('border-light');
$ct-side-navigation-light-link-child-hover-stripe-color: ct-color-light('highlight');
$ct-side-navigation-light-link-parent-active-stripe-color: ct-color-light('highlight');
$ct-side-navigation-light-link-child-active-stripe-color: ct-color-light('highlight');
$ct-side-navigation-dark-link-parent-stripe-color: ct-color-dark('border-light');
$ct-side-navigation-dark-link-parent-hover-stripe-color: ct-color-dark('highlight');
$ct-side-navigation-dark-link-child-stripe-color: ct-color-dark('border-light');
$ct-side-navigation-dark-link-child-hover-stripe-color: ct-color-dark('highlight');
$ct-side-navigation-dark-link-parent-active-stripe-color: ct-color-dark('highlight');
$ct-side-navigation-dark-link-child-active-stripe-color: ct-color-dark('highlight');
```

### Steps to reproduce

1. Go to [Storybook](https://uikit.civictheme.io/?path=/story/organisms-side-navigation--side-navigation) and observe the design of the component.
2. Compare to the [figma design](https://www.figma.com/design/HJJPc5auJT2xbsbcjB5lZP/CivicTheme%3A-Design-System-v1.7.0?node-id=2976-42296&t=x9kmUhOgwBsRi5cb-0) of the component.

### Observed outcome

They are different - missing the left stripe.

### Expected outcome

They should both contain the left stripe.

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: FAIL
Test Result:
- Left stripe is missing for child active items for both themes.

<img width="1230" alt="Screenshot 2024-06-13 at 10 08 29 PM" src="https://github.com/civictheme/uikit/assets/51696317/2bc16d34-0ce1-4964-99ed-ed6289999461">
<img width="865" alt="Screenshot 2024-06-13 at 10 12 58 PM" src="https://github.com/civictheme/uikit/assets/51696317/14574a93-b1b0-4dd8-8553-8a09b3222d42">

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- Left stripe is rendering for child active items for both themes.
<img width="390" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/e4be9cc1-278e-439a-ab16-24ed160850c6">
