### ISSUE TITLE
Radio label incorrectly labelled as 'Checkbox label'

### ISSUE THREAD

**Issue by fionamorrison23** [civictheme/uikit#244]
### Summary

The `Radio` atom is labelled 'Checkbox label' https://civictheme-uikit.netlify.app/?path=/story/atoms-form-controls-radio--radio

### Steps to reproduce

1. Go to: https://civictheme-uikit.netlify.app/?path=/story/atoms-form-controls-radio--radio
2. Note the label

### Observed outcome

The `Radio` atom is labelled 'Checkbox label'

### Expected outcome

It should be 'Radio label'

**Comment by fionamorrison23** [comment]
This issue has been reported elsewhere.

**Comment by AlexSkrypnyk** [comment]
This was related to Storybook storing knob values chosen on other pages.
Fixed in https://github.com/civictheme/uikit/issues/158
