### ISSUE TITLE
Add "generic" form control for unsupported input types

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#246]
These form controls are not currently provided as a custom styled component in the CT, but they are used in the implementations like Drupal theme.

```
<input type="date">
<input type="datetime-local">
<input type="email">
<input type="file">
<input type="hidden">
<input type="image">
<input type="month">
<input type="number">
<input type="password">
<input type="search">
<input type="tel">
<input type="time">
<input type="url">
<input type="week">
```

We need to create an `Input` component that will be used as a "catch-all" for all these types and would use the same look and feel as `textfield` (for simplicity). 

If a from control component will be later added to CT Figma - we will be able to implement just that component

Note that these input types need to be handled to not use the `textfield`'s styles.
```
<input type="color">
<input type="range">
```

**Comment by AlexSkrypnyk** [comment]
Closed in https://github.com/civictheme/uikit/pull/247

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- Input component has all mentioned  form controls types.
- They use the same look and feel as textfield.
<img width="1075" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/90cbb98b-5e07-4dfd-a02c-e601ec7af561">
