### ISSUE TITLE
Allow `Label` to accept raw content

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#273]
<h3 id="summary-problem-motivation">Problem/Motivation</h3>
Sometimes we need to add markup into the content of the Label component (e.g. a span tag to differentiate the text styling for a portion of the label)

<h4 id="summary-steps-reproduce">Steps to reproduce</h4>
Embed a Label and try adding markup to the "content" value.

<h3 id="summary-proposed-resolution">Proposed resolution</h3>
Modify the Label twig to support raw text (via a flag variable).

```
{#
/**
 * @file
 * Label component.
 *
 * Variables:
 * - content: [string] The label's content.
 * - is_raw_content: [boolean] Output text as raw value.
 * - size: [string] Label size: extra-large, large, regular, small, extra-small.
 * - theme: [string] Theme: light, dark.
 * - attributes: [string] Additional attributes.
 * - modifier_class: [string] Additional classes.
 */
#}

{% set size = size in ['extra-large', 'large', 'regular', 'small', 'extra-small'] ? size : 'regular' %}
{% set size_class = 'ct-label--%s'|format(size) %}
{% set theme_class = 'ct-theme-%s'|format(theme|default('light')) %}
{% set modifier_class = '%s %s %s'|format(theme_class, size_class, modifier_class|default('')) %}

{% if content is not empty -%}
  <label
    class="ct-label {{ modifier_class }}"
    {% if attributes is not empty %}{{ attributes|raw }}{% endif %}
  >
    {{ is_raw_content ? content|raw : content }}
  </label>
{%- endif %}
```

Add the flag variable to the story (label.stories.js) for the Label component:
```
// phpcs:ignoreFile
import { radios, text } from '@storybook/addon-knobs';
import CivicThemeLabel from './label.twig';

export default {
  title: 'Atoms/Label',
  parameters: {
    layout: 'centered',
  },
};

export const Label = (knobTab) => {
  const generalKnobTab = typeof knobTab === 'string' ? knobTab : 'General';

  const generalKnobs = {
    theme: radios(
      'Theme',
      {
        Light: 'light',
        Dark: 'dark',
      },
      'light',
      generalKnobTab,
    ),
    size: radios(
      'Size',
      {
        'Extra Large': 'extra-large',
        Large: 'large',
        Regular: 'regular',
        Small: 'small',
        'Extra Small': 'extra-small',
        None: '',
      },
      'regular',
      generalKnobTab,
    ),
    content: text('Content', 'Label content', generalKnobTab),
    is_content_text: boolean('Allow HTML in text', false, generalKnobTab),
    modifier_class: text('Additional classes', '', generalKnobTab),
    attributes: text('Additional attributes', '', generalKnobTab),
  };

  return CivicThemeLabel({
    ...generalKnobs,
  });
};

```

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- 'Allow HTML in content' attribute is disabled by default
- When enabled html markup is supported
- When disabled, html tags are stripped

<img width="1235" alt="Screenshot 2024-06-21 at 9 41 25 AM" src="https://github.com/civictheme/uikit/assets/51696317/43e746ed-c853-4566-985a-a5a3de8654e3">
<img width="1196" alt="Screenshot 2024-06-21 at 9 41 40 AM" src="https://github.com/civictheme/uikit/assets/51696317/7287030d-41f3-46cb-9ed6-6f3bd03d9fda">

When disabled, html tags are stripped
<img width="1230" alt="Screenshot 2024-06-21 at 9 44 43 AM" src="https://github.com/civictheme/uikit/assets/51696317/dbf36174-d168-47a1-a6fd-f024efdd990d">
