### ISSUE TITLE
`Label` on horizontal `Field` shrinks for small fields

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#277]
<img width="701" alt="735bdefa-b6a8-4d02-9fd2-8d67a0cf47a6" src="https://github.com/civictheme/uikit/assets/378794/1ac7109b-ea97-4330-8f25-9ec71180dbd2">

Te replicate in Storybook: remove description and message content

Note that the the whole `Field` component is always set to be `100%`. This allows the parent to control the width. With `horizontal` orientation it becomes much harder to predict the size of the label, especially when multiple fields are sitting on the form - they become look "odd" when their label width is not the same. So maybe the solution here is to add a parent class like `field-label-25` to set all labels of all instances of a `Field` component on the form to be the same size.

**Comment by AlexSkrypnyk** [comment]
Implemented to use `ct-field--with-fixed-labels--15` and `ct-field--with-fixed-labels--25` classes on the container.

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- Label on horizontal Field appear same size for small fields.
- New `Fixed label width` attribute works fine with `15 particles` and `25 particles` on desktop and mobile.
<img width="1108" alt="Screenshot 2024-06-23 at 11 26 18 PM" src="https://github.com/civictheme/uikit/assets/51696317/ccbdacc8-7e49-4bd2-8f32-5888da673b78">
<img width="1127" alt="Screenshot 2024-06-23 at 11 27 11 PM" src="https://github.com/civictheme/uikit/assets/51696317/e55a465d-cb79-4391-8a14-ab0cf392becd">
