### ISSUE TITLE
Icon on links wraps to a new line without a text

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#335]
![Atoms___Link_-_Link_⋅_Storybook](https://github.com/user-attachments/assets/29274d66-a8d4-4031-bd6c-0b6a790683f2)

This applies to the following compoinents:
- Link
- Content link
- Button

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- Icon on links wraps to a new line with a text.

| Components | Status | Screenshot |
|--------|--------|--------|
| Link | PASS | <img width="200" height="300" alt="Link" src="https://github.com/user-attachments/assets/cf845a07-dee4-4150-b9db-af762ef73078"> |
| Button | PASS | <img width="200" height="300" alt="Button" src="https://github.com/user-attachments/assets/a2893994-1252-4d7a-9309-3cd816dddf95"> | 
| Content Link | PASS | <img width="200" height="300" alt="content link" src="https://github.com/user-attachments/assets/042adb4c-d5e3-4268-867a-9d036301b91e">|
