### ISSUE TITLE
Comments in componenet twig files is not easily parsable due to inconsistencies.

### ISSUE THREAD

**Issue by alan-cole** [civictheme/uikit#342]
### Summary

Comments in componenet twig files is not easily parsable due to inconsistencies.

### Steps to reproduce

View twig file header on logo, tabs, video-player, navigation, webform.

### Observed outcome

Incorrect spelling of 'boolean', indentation, types.

### Expected outcome

Consistent and correct spelling of 'boolean', indentation, types.

**Comment by richardgaunt** [comment]
@alan-cole I have merged your PR - I believe this closes this issue.
