### ISSUE TITLE
WCAG 1.4.10 AA: Table breaks when site reflowed (Issue 19)

### ISSUE THREAD

**Issue by CJE001** [civictheme/uikit#387]
### Summary

Via Vision Australia assessment: August 2024

Impact: medium

Note: DTA have a 90 day remediation period to address the identified issues within the audit, all issues must be resolved to obtain WCAG 2.2 certification for digital.gov.au.

### Steps to reproduce

[Risk assessment for use of AI | digital.gov.au](https://www.digital.gov.au/policy/ai/risk-assessment) (https://www.digital.gov.au/policy/ai/risk-assessment)

### Observed outcome

When the site is viewed at an equivalent of 320 x 256 CSS pixels (1280 x 1024 CSS pixels at 400%), the visual layout of the "Risk matrix" table breaks, content overlaps, and the visual relationships are lost.

![Picture10](https://github.com/user-attachments/assets/c4511264-af82-45bb-b251-42bf8e1db125)

### Code used
```
<table>
<thead>
<tr>
<th>
&nbsp;
</th>
<th>
&nbsp;
</th>
<th colspan="5">
<p class="text-align-center ct-text-large">
Consequence
</p>
</th>
</tr>
<tr>
<th>
&nbsp;
</th>
<th>
&nbsp;
</th>
<th>
Insignificant
</th>
<th>
Minor
</th>
<th>
Moderate
</th>
<th>
Major
</th>
<th>
Severe
</th>
</tr>
</thead>
<tbody>
<tr>
<td rowspan="5" data-title="&nbsp;">
<p class="ct-text-large">
Likelihood
</p>
</td>
<td data-title="&nbsp;">
<strong>
Almost certain
</strong>
</td>
<td data-title="Consequence">
Medium
</td>
… 
</tr>
</tbody>
</table>
```
### Why this matters

Users with low vision who need to enlarge content may not be able to make sense of the table content or have access to the information it contains.  

### Expected outcome

Ensure that the table presentation is preserved when content is zoomed to 400% on a 1280px wide monitor. As tables are exempt from the horizontal scrolling restriction of this criterion, it is recommended that the table provide a horizontal scroll when content is reflowed. 

To ensure that the table can be reached and scrolled via keyboard in all browsers, add a `<div>` element around the table with a tabindex="0" attribute. 

As the `<div>` element is now focusable, it must be given an accessible name and role. This can be achieved with the `<region>` element (a generic landmark role) and the aria-labelledby attribute, referencing the table heading.

### Code example

```
<h3 id="table-heading">
Risk matrix
</h3>
<div role="region" aria-labelledby="table-heading" tabindex="0">
<table>
…
</table>
</div>
```
**Note**

Content is exempt from the horizontal scrolling restriction if it requires a two-dimensional presentation for understanding. For example, images, maps, diagrams, video, games, presentations, data tables, and interfaces where it is necessary to keep toolbars in view while manipulating content.

### Related issues

For other issues related to this component, please refer to:

•	Issue 4 – Complex table headers not correctly marked up
•	Issue 15 – Loss of table content when text resized: https://github.com/civictheme/uikit/issues/386

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- When 'Data table' prob is enabled then 2 dimensional table style does not break at various viewports.

https://github.com/user-attachments/assets/c9353da5-9df7-4150-b2d1-cc4d6870d495
