### ISSUE TITLE
[DEFECT] Design: Footer design in 1.8 has empty space added

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#399]
<img width="477" alt="CivicTheme__Design_System_v1_8_0_–_Figma" src="https://github.com/user-attachments/assets/9c35f58e-3016-48f7-9aa8-df95f47b6111">

Can you please revert this change in the Figma or provide more information about why that change was introduced.

**Comment by fionamorrison23** [comment]
@AlexSkrypnyk  I can see the design is like this back in 1.4. However, this is not the case in code. The footer is displaying as expected on the CivicTheme sites. I'll have @alanrako update the design. Thanks for raising.

**Comment by alanrako** [comment]
@fionamorrison23 
Updated the desktop design so the footer displays 4 columns of equal width.
Please approve.
![Device=Desktop, Dark Theme=False](https://github.com/user-attachments/assets/790e6624-34cd-4bde-a69a-7dcdef44b182)
![Device=Desktop, Dark Theme=True](https://github.com/user-attachments/assets/3a22fea4-2f59-4787-bca0-48dd6341ed29)
