### ISSUE TITLE
Left and right padding missing on 'Quote' component

### ISSUE THREAD

**Issue by fionamorrison23** [civictheme/uikit#46]
### Summary

When the `Quote` component is used on a page with no TOC there are no left or right padding esulting in the component displaying to the very edge of the screen.

### Steps to reproduce

1. Create a Page content type, filling in the required fields
2. Select 'Hide sidebar' in 'Appearance' settings
3. Open the 'Component' select box and choose 'Quote'
4. Add content
5. Save and observe the front end

### Observed outcome

There is no left or right margins when the sidebar navigation is hidden

**Desktop**
<img width="1897" alt="Screenshot 2023-11-30 at 4 55 17 pm" src="https://github.com/salsadigitalauorg/civictheme_source/assets/125337363/c0b31cff-606b-4d86-8d9a-601aec0a4b4f">

**Mobile**
<img width="388" alt="Screenshot 2023-11-30 at 5 00 46 pm" src="https://github.com/salsadigitalauorg/civictheme_source/assets/125337363/d3e363a6-939b-4d3d-9da3-cac1d44ac561">

### Expected outcome

The quote component should have the same left and right spacing as other components that use the full page body with such as the 'Promo'

**Comment by AlexSkrypnyk** [comment]
@fionamorrison23 
The Quote component is a content-based component. It has been incorrectly used at an Organism-level by implementations in the Drupal theme and it should be removed from that implementations. This work is tracked here - https://www.drupal.org/node/3415738

As for this ticket - I suggest we close it as the current implementation does not have any issues when the Quote component is used in the Content.
