### ISSUE TITLE
A11Y: Radio buttons are not grouped programmatically

### ISSUE THREAD

**Issue by fionamorrison23** [civictheme/uikit#56]
### Summary

The 'Pick a filter' radio buttons are not grouped programmatically.

When radio buttons are not grouped programmatically, a screen reader user misses out on the context provided through the radio group label as focus moves directly to the radio buttons.

<img width="639" alt="Screenshot 2023-02-26 at 12 04 59 pm" src="https://user-images.githubusercontent.com/125337363/221386840-cb96127f-f2f9-4213-98fe-30672f292907.png">

### Steps to reproduce

See description

### Observed outcome

Radio buttons are not grouped programmatically

### Expected outcome

Radio buttons are grouped programmatically

### Auditor’s recommendation
Wrap the radio buttons in a `<fieldset>`.
Mark up 'Pick a filter' as a `<legend>` element to provide a group label. 
Use CSS to provide the same visual styling.

**Comment by AlexSkrypnyk** [comment]
Our new Radios and Checkboxes are grouped without `<fieldset>`. Using `<fieldset>` for grouping is not a WCAG requirement but rather a stylistic choice. 
https://www.w3.org/WAI/tutorials/forms/grouping/#radio-buttons
