### ISSUE TITLE
Field - Create

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#58]
See epic: https://github.com/civictheme/uikit/issues/121

`Field` is a molecule-level component used as a centralised way to create controls. The consumers should use this component when form controls are required.

## SD

1. Refactor current `Form element` into `Field` component using [this code](https://github.com/civictheme/monorepo-drupal/blob/feature/CIVIC-831-form-element-refactor/docroot/themes/contrib/civictheme/civictheme_library/components/02-molecules/field/field.twig) for reference. 
2. Update SCSS for all Form control atoms to use a set of `ct-field-*` variables instead of per-control variables: this will centralise how these look and feel is controlled from CSS. Use additional variables for specific controls if required. Use [this code](https://github.com/civictheme/monorepo-drupal/blob/feature/CIVIC-831-form-element-refactor/docroot/themes/contrib/civictheme/civictheme_library/components/00-base/_variables.components.scss#L405) for reference (note that the variables there are name-spaced incorrectly).
3. Update component to correctly use all updated atom components + update storybook.
4. Update component to use new helpers instead of using its own and decommission existing helpers.

**Comment by AlexSkrypnyk** [comment]
This is now complete. Still need to update `Fieldset` and `Field Group`.

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- Verified `Field` component with form elements
- Verified various properties such as inline, orientation, required with form elements
<img width="1012" alt="Screenshot 2024-06-15 at 11 22 01 AM" src="https://github.com/civictheme/uikit/assets/51696317/711e8049-df3e-4f07-9f1a-30c79828fdfb">
<img width="1029" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/5a12c7c9-56d9-4be7-a4b9-75a18a873eac">
<img width="856" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/a9cb831b-2055-400d-8586-e1836cb5e059">
