### ISSUE TITLE
Field Group, Group filter, Pagination, List - Update to use `Field`

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#59]
See epic: https://github.com/civictheme/uikit/issues/121

## SD

1. Update `Group`, `Group filter`, `Pagination`, `List` components to use the new `Field` component.
2. Update component to use new helpers instead of using its own and decommission existing helpers.

**Comment by AlexSkrypnyk** [comment]
moved to D.O.: https://www.drupal.org/project/civictheme/issues/3415678

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
 | Issues | Status |
|--------|--------|
| Input component: Calendar and clock icons for dark theme are not visible</br>Type : Date, Month, Time, Week. |This is fixed. </br> PASS |
| Field component - Horizontal Orientation - No description and message content : Then Field label is not correctly aligned with input types such as Textfield, Email, Color. | New ticket created as [`Label` on horizontal `Field` shrinks for small fields · Issue #277 · civictheme/uikit](https://github.com/civictheme/uikit/issues/277) |
| Group-filter : we have description in the dropdown however no attribute to remove it. | This is fixed, description does not render in dropdown. </br> PASS |
| Pagination :</br>Active is link and Ellipsis attributes are not working.</br>Pagination number is missing on mobile. | New defect ticket [Component - Pagination issues · Issue #280  · civictheme/uikit](https://github.com/civictheme/uikit/issues/280) . |

**Screenshots:**
<img width="1208" alt="Screenshot 2024-06-21 at 12 22 01 PM" src="https://github.com/civictheme/uikit/assets/51696317/9b1c83cf-265f-4403-b362-98e192e584f4">

<img width="1215" alt="Screenshot 2024-06-21 at 12 25 41 PM" src="https://github.com/civictheme/uikit/assets/51696317/b9206132-9475-41b5-ba2f-30c343fd3992">
