### ISSUE TITLE
Radio group - Create

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#61]
See epic: https://github.com/civictheme/uikit/issues/121

This is a new atom component that allows to group radios.

## SD

1. Create a new component using designs in Figma v1.7.0. Use [this code](https://github.com/civictheme/monorepo-drupal/blob/feature/CIVIC-831-form-element-refactor/docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/radio-group/radio-group.twig) for reference.
2. Update component to correctly use [updated](https://github.com/civictheme/uikit/issues/80) `Radio`'s props.
3. Update component to use new helpers instead of using its own and decommission existing helpers.

**Comment by fionamorrison23** [comment]
@joshua-salsadigital https://www.figma.com/file/HJJPc5auJT2xbsbcjB5lZP/CivicTheme%3A-Design-System-v1.7.0?type=design&node-id=2976%3A39056&mode=design&t=ZTWjKc2uzmVpIANB-1

**Comment by AlexSkrypnyk** [comment]
This component was merged into Field. The generation of the a group of radios now takes place in Field.

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- Radio group in Field component works fine
- Has design as per Figma for various properties such as inline, orientation
<img width="1206" alt="Screenshot 2024-06-14 at 12 49 25 PM" src="https://github.com/civictheme/uikit/assets/51696317/131422f4-4c92-4c06-8b73-31dc63a09873">
<img width="1175" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/d4a7ec28-9786-4a26-8047-8bc0118c646b">
<img width="1045" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/8328c94c-4805-42e5-b842-6eeab286eaf9">
