### ISSUE TITLE
Checkbox - Update to design 1.7

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#67]
See epic: https://github.com/civictheme/uikit/issues/121

We are looking for a bulletproof, icon-less and customisable implementation of a checkbox using CSS-only.

## SD

1. Update the implementation to match all states in Figma v1.7.0. Note that some of the states were fixed in Figma, so these should be reflected in code. Use [this code](https://github.com/civictheme/monorepo-drupal/blob/feature/CIVIC-831-form-element-refactor/docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/checkbox/checkbox.twig) for reference.
2. Update component to correctly use [updated](https://github.com/civictheme/uikit/issues/125) `Label`'s props for `for` and `required`.
3. Update component to use new helpers instead of using its own and decommission existing helpers.

**Comment by fionamorrison23** [comment]
Awaiting design.

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: FAIL
Test Result:
1. Border radius of checkbox is 2px. Expected is 4px as per Figma.
2. Checkbox border and background colour for `Disabled Checked` state is incorrect. It should be same as `Disabled unchecked` state

**Issue#1:**
<img width="1213" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/cbebe5e6-abbd-44c9-a0d4-6138214e0642">

**Issue#2:**
<img width="1234" alt="Screenshot 2024-06-13 at 10 45 09 AM" src="https://github.com/civictheme/uikit/assets/51696317/11b7fe80-bb26-4434-95b5-46d498ef736e">

**Comment by AlexSkrypnyk** [comment]
1. Acknowledged. Fixed now. Also, some sub-pixel sizing dimensions were fixed.
<img width="77" alt="Cursor_and_Molecules___Field_-_Field_⋅_Storybook" src="https://github.com/civictheme/uikit/assets/378794/622f17cc-5de9-4aab-89cb-f900de948c65">


2. We are not updating the background for the disabled state - we are making the whole control semi-transparent. This is an industry standard practice as it also takes care of the label.

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- Retested issue#1 and it is fixed, border radius of checkbox is 4px.
- Border width pixel is also now better.

<img width="1239" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/38c8cff1-e5bb-40ba-99aa-8894e96119cd">
