### ISSUE TITLE
Update the styling on search page to match designs

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#70]
<img width="313" alt="_CIVIC-1552__Update_the_styling_on_search_page_to_match_designs_-_JIRA" src="https://github.com/civictheme/uikit/assets/378794/5a54dbe5-4038-44a5-8d2a-17576aeed83e">

**Comment by fionamorrison23** [comment]
Closing. See https://www.drupal.org/project/civictheme/issues/3421778
