### ISSUE TITLE
Radio - Update to design 1.7

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#80]
See epic: https://github.com/civictheme/uikit/issues/121

We are looking for a bulletproof, icon-less and customisable implementation of a radio using CSS-only.

## SD

1. Update the implementation to match all states in Figma v1.7.0. Note that some of the states were fixed in Figma, so these should be reflected in code. Use [this code](https://github.com/civictheme/monorepo-drupal/blob/feature/CIVIC-831-form-element-refactor/docroot/themes/contrib/civictheme/civictheme_library/components/01-atoms/radio/radio.twig) for reference.
2. Update component to correctly use [updated](https://github.com/civictheme/uikit/issues/125) `Label`'s props for `for` and `required`.
3. Update component to use new helpers instead of using its own and decommission existing helpers.

**Comment by fionamorrison23** [comment]
@joshua-salsadigital l https://www.figma.com/file/HJJPc5auJT2xbsbcjB5lZP/CivicTheme%3A-Design-System-v1.7.0?type=design&node-id=2976%3A39056&mode=design&t=ZTWjKc2uzmVpIANB-1
I believe there was some rework required after the entire Form elements epic was groomed.

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: FAIL
Test Result:
- Radio border and background colour for Disabled Checked state is incorrect. It should be same as Disabled unchecked state for both themes.

<img width="1205" alt="Screenshot 2024-06-13 at 12 04 10 PM" src="https://github.com/civictheme/uikit/assets/51696317/a1c2de3b-6ad1-4cc2-9062-36b79c6e2b97">

**Comment by sonamchaturvedi28** [comment]
Test Env: DEV
Test Status: PASS
Test Result:
- Radio design is as per Figma

<img width="1172" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/ae1a6eda-7ae9-41e1-8c74-66f3812c283b">
<img width="1220" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/677a195c-d4f1-48bb-8d0b-c40c1f891dad">
