### ISSUE TITLE
Content in table cells should be top aligned

### ISSUE THREAD

**Issue by fionamorrison23** [civictheme/uikit#90]
### Description
Content in table cells is centre aligned. It should be top aligned.
### Steps to reproduce

1. Create a table with at least two columns
2. Insert a small amount of content on one cell
3. Insert a larger amount of content in the cell to the left or the right
4. Save and view the front end
### Observed
The content in the cell with very little content is centre aligned. See attached screenshot.
### Expected
Content should be top aligned.
![Screenshot 2024-02-23 at 8 46 45 am](https://github.com/civictheme/uikit/assets/125337363/8711c70d-5a82-4d50-840b-59403cfbd96a)

**Comment by fionamorrison23** [comment]
@joshua-salsadigital can you please pick this up. This is the same fix we just did on the current project. Thanks.

**Comment by AlexSkrypnyk** [comment]
@sonamchaturvedi28 
please test at https://civictheme-uikit.netlify.app/?path=/story/atoms-table--table

**Comment by sonamchaturvedi28** [comment]
Test link: https://civictheme-uikit.netlify.app/?path=/story/atoms-table--table
Test Status: PASS
Test Result:
- Content in table cells is top aligned.
<img width="1440" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/f00fa67f-04a1-4ae0-ac7d-a26c1b7944ce">
