### ISSUE TITLE
Links within Campaign and Slider components do not show external icons

### ISSUE THREAD

**Issue by richardgaunt** [civictheme/uikit#92]
See: https://github.com/civictheme/uikit/blob/main/components/03-organisms/campaign/campaign.twig#L100

There should be a `is_external` property being passed to button.twig but there is not. 
The drupal paragraph preprocess passes `is_external` which obviously isn't being utilised at the moment.

**Comment by richardgaunt** [comment]
PR here: https://github.com/civictheme/uikit/pull/93

**Comment by fionamorrison23** [comment]
@AlexSkrypnyk please review. Thanks.

**Comment by AlexSkrypnyk** [comment]
@sonamchaturvedi28 
please test in https://civictheme-uikit.netlify.app/

please do note that changing the number of levels when `None` is selected does trim the levels.
<img width="854" alt="Window_and_Organisms___Navigation_-_Navigation_⋅_Storybook" src="https://github.com/civictheme/uikit/assets/378794/62406adc-e1dd-4943-89b7-3f7eb512f13a">

**Comment by AlexSkrypnyk** [comment]
@sonamchaturvedi28 
When testing, please note that it is not possible to control whether randomly generated links are external or not - please use the slider below to add links and some of them will be external.

<img width="831" alt="Window_and_Organisms___Campaign_-_Campaign_⋅_Storybook" src="https://github.com/civictheme/uikit/assets/378794/61393f40-dca5-4963-bbc5-de09c6aec3a7">

**Comment by sonamchaturvedi28** [comment]
Test links: https://civictheme-uikit.netlify.app/?path=/story/organisms-slider--slider and https://civictheme-uikit.netlify.app/?path=/story/organisms-campaign--campaign
Test Status: PASS
Test Result:
- External links within Campaign and Slider components now show external icons

<img width="1434" alt="Screenshot 2024-03-11 at 3 00 00 PM" src="https://github.com/civictheme/uikit/assets/51696317/d8b64673-47fb-4cfc-83bc-4140cef414e6">

<img width="1407" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/c4dc23b1-61c7-4eae-88ae-4458d92bedb8">
