### ISSUE TITLE
Navigation component does not trim menu levels to the first level when `none` is selected

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#96]
When `none` is used for the `dropdown` prop, the multi-level menu is not currently trimmed to contain only the top-most level.

While consumer implementations can control the hierarchy sent to the component, it is the expectation that the component's `dropdown' prop will be able to guarantee consistent look and feel.

We need to update the behaviour of the `Navigation` component to only out put the first level of the multi-level menu structure when `none` is used for the `dropdown` prop.

**Comment by AlexSkrypnyk** [comment]
@sonamchaturvedi28 
please test in https://civictheme-uikit.netlify.app/

please do note that changing the number of levels when `None` is selected does trim the levels.
<img width="854" alt="Window_and_Organisms___Navigation_-_Navigation_⋅_Storybook" src="https://github.com/civictheme/uikit/assets/378794/62406adc-e1dd-4943-89b7-3f7eb512f13a">

**Comment by sonamchaturvedi28** [comment]
Test link: https://civictheme-uikit.netlify.app/
Test Status: PASS
Test Result: 
- When `none` is used for the dropdown prop, the multi-level menu is now trimmed to contain only the top-most level.

<img width="1440" alt="image" src="https://github.com/civictheme/uikit/assets/51696317/86dec51a-2348-45c1-8495-e18b5e8a7181">
